name: test
on: push

jobs:
  nodejob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo ${{ github.ref }}
      - run: echo ${{ GITHUB_REF }}
