name: test
on: push

jobs:
  nodejob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run command
      - run:
        echo ${{github.ref}}
        echo ${{GITHUB_REF}}
